//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj1091613.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableStar1091613
    {
        public string StrId { get; set; }
        public string StrName { get; set; }
        public string StrClass { get; set; }
        public Nullable<int> SCId { get; set; }
    }
}
