//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj1091613.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;

    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public partial class TableAcquisition1091613
    {
        [DisplayName("收購編號")]

        [StringLength(5, ErrorMessage = "帳號必須是5個字元", MinimumLength = 5)]
        public string AId { get; set; }

        [DisplayName("會員帳號")]
        [StringLength(15, ErrorMessage = "帳號必須是3~15個字元", MinimumLength = 3)]
        public string ANo { get; set; }

        [DisplayName("收購物品")]
        [Required(ErrorMessage = "收購物品不可空白")]
        [StringLength(15, ErrorMessage = "最多15個字", MinimumLength = 0)]
        public string AName { get; set; }

        [DisplayName("收購預算價格")]
        [Required(ErrorMessage = "價格不可空白")]
        public Nullable<int> APrice { get; set; }

        [DisplayName("備註")]
        [StringLength(20, ErrorMessage = "備註最多20字", MinimumLength = 0)]
        public string ARemark { get; set; }
    }
}
